### ISSUE TITLE
Enhancement - Log Tab Title

### ISSUE THREAD

**Issue by barcar** [jdrews/logstation#71] opened 2023-04-06 09:30 UTC
Great project. Thank you.

The tabs for log files display the name truncated from the start of the path. Like "/some/folder/..." but, in my opinion, it would be better to show the end of the path like "../log/service.log" (and truncate at the start).

I know that you can hover over the tab to see the full file path but I thought this might be easier.

Alternatively, it would be cool to provide some way to specify the tab title for a particular log in the config file. This might not work so well for wildcards.

And it would be great if you could specify a tab colour for a particular log (or set of logs).

**Comment by jdrews** [comment] 2023-04-07 16:42
Thank you! 

I think this is working correctly on [v2.0.0-beta2](https://github.com/jdrews/logstation/releases/tag/v2.0.0-beta2). Can you try it there? 
![image](https://user-images.githubusercontent.com/172766/230645566-57314e2c-417e-4293-895e-d10965f329ba.png)

**Comment by jdrews** [comment] 2023-04-07 16:51
Related but not the same as #5 

> And it would be great if you could specify a tab colour for a particular log (or set of logs).

**Comment by barcar** [comment] 2023-04-07 17:28
Not quite…

File '/mnt/docker/volumes/homebridge_data/_data/homebridge.log' shows up as '...mnt/docker/volumes//'

[Image.png]

________________________________

**Comment by barcar** [comment] 2023-04-07 17:33
Not quite…

File '/mnt/docker/volumes/homebridge_data/_data/homebridge.log' shows up as '...mnt/docker/volumes//'

![IMG_0401](https://user-images.githubusercontent.com/2155858/230652097-976a72c9-3da7-49d6-95cc-e9b96f39262d.jpeg)

**Comment by jdrews** [comment] 2023-04-07 22:17
Oh interesting! Thanks for the screenshot and example log file names. I'll try that out here and see if I can recreate to fix it. Thanks!

**Comment by jdrews** [comment] 2023-04-12 16:52
I tried using the same path and filename as stated above and I couldn't get to behave as shown in your screenshot. 

I'll try running logstation in a docker container to see if it behaves any differently. 

What browser were you using? I've tried it on the latest Chrome and Firefox, both of which worked as expected.

**Comment by barcar** [comment] 2023-04-12 20:04
I was using Safari.
________________________________

**Comment by jdrews** [comment] 2023-04-17 03:05
I was able to reproduce the problem where the logfile gets text-overflow ellipsed on the right side instead of the left. This only seems to happen on Safari. I couldn't get my CSS magic to work on Safari, so instead I'm picking up when it's Safari and only showing the filename and not the path.

![image](https://user-images.githubusercontent.com/172766/232368060-554607ce-7a7a-4169-b488-04d3e9092b3d.png)

I made a new beta release. Please try it out and let me know how it goes. 
https://github.com/jdrews/logstation/releases/tag/v2.0.0-beta3

**Comment by jdrews** [comment] 2023-04-17 03:09
By the way, do you happen to have a M1 or M2 mac? (darwin_arm64)? I made a build for that but I haven't been able to test it since I don't have access to that type of hardware.

**Comment by barcar** [comment] 2023-04-29 14:42
Apologies for the delay. The new version works perfectly in Safari. I'm afraid my Mac is not Apple silicon.

**Comment by jdrews** [comment] 2023-04-29 14:59
Great! Thanks for logging this issue and trying out the fix! I'm going to close this issue out.

**Closed by jdrews** 2023-04-29 14:59 UTC
Labels: enhancement
